# Generated by Django 6.0.3 on 2026-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_analyze'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='tool_type',
            field=models.CharField(default='Sentiment Analysis', max_length=50),
        ),
    ]
