# Generated by Django 6.0.3 on 2026-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_analyze_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='sentiment_label',
            field=models.CharField(default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='analyze',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyze',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
