# Generated by Django 6.0.3 on 2026-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_analyze_sentiment_label_analyze_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='neg_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='analyze',
            name='neu_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='analyze',
            name='pos_score',
            field=models.FloatField(default=0),
        ),
    ]
