# Generated by Django 6.0.3 on 2026-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_analyze_neg_score_analyze_neu_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
