# Generated by Django 6.0.3 on 2026-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_analyze_summary_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='tool_type',
            field=models.CharField(max_length=50),
        ),
    ]
