# Generated by Django 6.0.3 on 2026-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_alter_analyze_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='keyword_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
